/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IArbiSecure {
    struct Condition {
        uint8 conditionType;
        uint256 threshold;
        address oracle;
    }

    struct Milestone {
        string title;
        uint256 amount;
        Condition[] conditions;
    }

    function initialize(address staking_token) external;

    function getAdmin() external view returns (address);

    function getProtocolFee() external view returns (uint256);

    function isPaused() external view returns (bool);

    function getDealCount() external view returns (uint256);

    function getDisputeCount() external view returns (uint256);

    function hasUsedGaslessDeal(address user) external view returns (bool);

    function setProtocolFee(uint256 new_fee) external;

    function pause() external;

    function unpause() external;

    function transferAdmin(address new_admin) external;

    function configStaking(address token, uint256 min_amount) external;

    function createDeal(
        uint256 _ref_id,
        address freelancer,
        address arbiter,
        address token,
        uint256 amount,
        Milestone[] memory milestones
    ) external payable;

    function registerAsArbiter(uint256 amount) external;

    function releaseMilestone(
        uint256 deal_id,
        uint256 milestone_index
    ) external;

    function slashArbiter(
        address arbiter,
        uint256 amount,
        uint8 reason
    ) external;

    function raiseDispute(
        uint256 deal_id,
        string calldata reason,
        string calldata evidence_cid
    ) external;

    function resolveDispute(
        uint256 dispute_id,
        uint256 client_share,
        uint256 freelancer_share
    ) external;
}
