/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IArbiSecure {
  export type ConditionStruct = {
    conditionType: BigNumberish;
    threshold: BigNumberish;
    oracle: AddressLike;
  };

  export type ConditionStructOutput = [
    conditionType: bigint,
    threshold: bigint,
    oracle: string
  ] & { conditionType: bigint; threshold: bigint; oracle: string };

  export type MilestoneStruct = {
    title: string;
    amount: BigNumberish;
    conditions: IArbiSecure.ConditionStruct[];
  };

  export type MilestoneStructOutput = [
    title: string,
    amount: bigint,
    conditions: IArbiSecure.ConditionStructOutput[]
  ] & {
    title: string;
    amount: bigint;
    conditions: IArbiSecure.ConditionStructOutput[];
  };
}

export interface IArbiSecureInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "configStaking"
      | "createDeal"
      | "getAdmin"
      | "getDealCount"
      | "getDisputeCount"
      | "getProtocolFee"
      | "hasUsedGaslessDeal"
      | "initialize"
      | "isPaused"
      | "pause"
      | "raiseDispute"
      | "registerAsArbiter"
      | "releaseMilestone"
      | "resolveDispute"
      | "setProtocolFee"
      | "slashArbiter"
      | "transferAdmin"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "configStaking",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDeal",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      IArbiSecure.MilestoneStruct[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "getAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDealCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasUsedGaslessDeal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsArbiter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slashArbiter",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "configStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDealCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUsedGaslessDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsArbiter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashArbiter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export interface IArbiSecure extends BaseContract {
  connect(runner?: ContractRunner | null): IArbiSecure;
  waitForDeployment(): Promise<this>;

  interface: IArbiSecureInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  configStaking: TypedContractMethod<
    [token: AddressLike, min_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  createDeal: TypedContractMethod<
    [
      _ref_id: BigNumberish,
      freelancer: AddressLike,
      arbiter: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      milestones: IArbiSecure.MilestoneStruct[]
    ],
    [void],
    "payable"
  >;

  getAdmin: TypedContractMethod<[], [string], "view">;

  getDealCount: TypedContractMethod<[], [bigint], "view">;

  getDisputeCount: TypedContractMethod<[], [bigint], "view">;

  getProtocolFee: TypedContractMethod<[], [bigint], "view">;

  hasUsedGaslessDeal: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [staking_token: AddressLike],
    [void],
    "nonpayable"
  >;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  raiseDispute: TypedContractMethod<
    [deal_id: BigNumberish, reason: string, evidence_cid: string],
    [void],
    "nonpayable"
  >;

  registerAsArbiter: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseMilestone: TypedContractMethod<
    [deal_id: BigNumberish, milestone_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [
      dispute_id: BigNumberish,
      client_share: BigNumberish,
      freelancer_share: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setProtocolFee: TypedContractMethod<
    [new_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  slashArbiter: TypedContractMethod<
    [arbiter: AddressLike, amount: BigNumberish, reason: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [new_admin: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "configStaking"
  ): TypedContractMethod<
    [token: AddressLike, min_amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDeal"
  ): TypedContractMethod<
    [
      _ref_id: BigNumberish,
      freelancer: AddressLike,
      arbiter: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      milestones: IArbiSecure.MilestoneStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDealCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDisputeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProtocolFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasUsedGaslessDeal"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[staking_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [deal_id: BigNumberish, reason: string, evidence_cid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAsArbiter"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseMilestone"
  ): TypedContractMethod<
    [deal_id: BigNumberish, milestone_index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      dispute_id: BigNumberish,
      client_share: BigNumberish,
      freelancer_share: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProtocolFee"
  ): TypedContractMethod<[new_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashArbiter"
  ): TypedContractMethod<
    [arbiter: AddressLike, amount: BigNumberish, reason: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[new_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
