/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IArbiSecure } from "./IArbiSecure";
export * as factories from "./factories";
export { IArbiSecure__factory } from "./factories/IArbiSecure__factory";
